import "./globals.css";
import { Inter } from "next/font/google";

import FollowBar from "@/components/followbar/FollowBar";
import Sidebar from "@/components/sidebar/Sidebar";
import LoginModal from "@/components/modals/LoginModal";
import RegisterModal from "@/components/modals/RegisterModal";
import EditModal from "@/components/modals/EditModal";

import AuthContext from "./context/AuthContext";
import ToasterContext from "./context/ToasterContext";

import getCurrentUser from "./actions/getCurrentUser";
import { User } from "@prisma/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <AuthContext>
        <body className={`min-h-screen text-white ${inter.className}`}>
          {/* Provides toast notification to end-user */}
          <ToasterContext />
          {/* Modals to facilitate form view for signing in and registration */}
          <LoginModal />
          <RegisterModal />
          <EditModal currentUser={currentUser as User} />
          <div className="container h-full mx-auto xl:px-30 max-w-full">
            <div className="grid grid-cols-4 h-full">
              {/* Sidebar section present on the left hand side ---> Built with Mobile first approach */}
              <Sidebar />

              {/* ---------Main--------- */}
              <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-500/30">
                {children}
              </div>
              {/* ---------Main--------- */}

              {/* Follow section present on the right hand side */}
              <FollowBar />
            </div>
          </div>
        </body>
      </AuthContext>
    </html>
  );
};

export default RootLayout;
